GET /api/v1/patients
GSG-G9/dentoro pull request #30
Opened 2021-03-29 09:04 UTC by Alaalser

2021-03-29 13:31 UTC, hassanelnajjar commented on server/test/index.test.js
> +beforeEach(() => dbBuild());
Hi Alaa,Please put beforeEach and After Each inside the describe

2021-03-29 13:31 UTC, hassanelnajjar commented on server/test/index.test.js
> +  test('Route /patients status 200, json header', async () => {
Also,please make a new test for the database query

2021-03-29 13:31 UTC, hassanelnajjar commented on server/test/index.test.js
> +    expect(res.body.data).toHaveLength(20);
you can add return here before expect like this and remove the expect.assertions(1);
```js
return expect(res.body.data).toHaveLength(20);
```

2021-03-29 13:31 UTC, hassanelnajjar commented on package.json
> +}
Please Add Line at the end.

2021-03-29 13:31 UTC, hassanelnajjar commented on .circleci/config.yml
> +      - test
Please Add Line at the end.

2021-03-29 22:13 UTC, hassanelnajjar approved these changes

2021-03-30 09:31 UTC, hassanelnajjar approved these changes

2021-03-30 09:38 UTC, Mu7ammadAbed commented on .circleci/config.yml
> +
Fix this

2021-03-30 11:31 UTC, hassanelnajjar approved these changes

2021-03-30 12:17 UTC, Mu7ammadAbed requested changes

2021-03-30 12:17 UTC, Mu7ammadAbed commented on server/routes/patients/index.js
> +router.route('/:patientId').get(getAllProfileData).patch();
Remove the repeated lines

2021-03-30 12:35 UTC, Mu7ammadAbed approved these changes

2021-03-30 13:21 UTC, merged