Booking Form
GSG-G9/dentoro pull request #88
Opened 2021-04-13 18:56 UTC by Alaalser

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/index.js
> +          <Input placeholder="Appointment date" />
Please use here DataPicker

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/index.js
> +          <Input placeholder="Appointment time" />
Please use here TimePicker

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/index.js
> +          <Input placeholder="Complaints" className="input-height" />
I Think you need to use Input.TextArea here instead of input.

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/index.js
> +          <Input placeholder="Diseases" className="input-height" />
I Think you need to use Input.TextArea here instead of input.

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/index.js
> +          <Input placeholder="Email" />
Please use input with type=email

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/index.js
> +          <Input placeholder="Birthday" />
Please use DatePicker here

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/index.js
> +          <Input placeholder="Phone" />
The Phone is the main input in our application, as you know it should be unique and with a specific format, So I think you need to add some validation to it, so the user have to enter it in the same shape every time
+970 - 59 - 759-5893
By Apply this format, the user will enter the phone number in the correct format every time

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/style.css
> +}
We have a problem in our eslint configuration with CSS ,So please add a line here and pay attention to css file every time :(

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/index.js
> +      setSuccess(false);
Why you set Success to false here , it's already false ?

2021-04-13 21:45 UTC, hassanelnajjar commented on client/src/components/BookingForm/index.js
> +
I think you need to add loading here ?

2021-04-14 22:07 UTC, Mu7ammadAbed requested changes

2021-04-14 22:07 UTC, Mu7ammadAbed commented on client/src/pages/LandingPage/index.js
> +import NavTap from '../../components/NavTap';
Edit this component name here and the original one
```suggestion
import Navbar from '../../components/Navbar';
```

2021-04-15 02:50 UTC, Mu7ammadAbed requested changes

2021-04-15 02:50 UTC, Mu7ammadAbed commented on client/src/components/BookingForm/index.js
> +            />
```suggestion
            <TimePicker
              placeholder="Appointment time"
              value={time}
              onChange={onTime}
              format="HH"
              disabledHours={() => [0, 1, 2, 3, 4, 5, 6, 7, 19, 20, 21, 22, 23]}
              hideDisabledOptions
              showNow={false}
            />
```

2021-04-15 02:50 UTC, Mu7ammadAbed commented on client/src/components/BookingForm/style.css
> +    }
```suggestion
    display: flex;
    justify-content: center;
    }

    .booking .ant-form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
```

2021-04-15 02:50 UTC, Mu7ammadAbed commented on client/src/components/BookingForm/style.css
> +}
```suggestion
```

2021-04-15 02:50 UTC, Mu7ammadAbed commented on client/src/components/BookingForm/style.css
> +}
```suggestion
}
.success {
    display: flex;
    flex-direction: column;
    justify-content: center;
    min-height: 70vh;
}

.booking .ant-result-success {
    padding: 0;
    margin-bottom: 3em;
}
```

2021-04-15 02:55 UTC, Mu7ammadAbed requested changes

2021-04-15 02:55 UTC, Mu7ammadAbed commented on client/src/components/BookingForm/style.css
> +    margin-left: 12rem;
```suggestion
```

2021-04-15 02:55 UTC, Mu7ammadAbed commented on client/src/components/BookingForm/style.css
> +}
```suggestion
.success {
    display: flex;
    flex-direction: column;
    justify-content: center;
    min-height: 70vh;
}
```

2021-04-15 02:55 UTC, Mu7ammadAbed commented on client/src/components/BookingForm/style.css
> +}
```suggestion
.booking .ant-result-success {
    padding: 0;
    margin-bottom: 3em;
}
```

2021-04-15 13:41 UTC, Mu7ammadAbed approved these changes

2021-04-15 13:42 UTC, AlaaShurrab approved these changes

2021-04-15 13:43 UTC, hassanelnajjar approved these changes

2021-04-15 13:44 UTC, merged